plugins:
  rstudio_composer_template_enabled:
    default: true
    client: true
  rstudio_composer_template_category:
    default: ""
    type: "category_list"
    client: true
  rstudio_jobs_category:
    default: ""
    type: "category"
    client: true
